### ISSUE TITLE
Unhandled TaskCanceledException by the FetchFeatureTogglesTask

### ISSUE THREAD

**Issue by rafaelpadovezi** [Unleash/unleash-client-dotnet#152] opened 2023-08-07 18:06 UTC
**Describe the bug**
Not sure if is a bug or the intended behavior. If the call to features API throws a timeout error (`TaskCanceledException`) the unleash is not initialized, considering a synchronous initialization. The [current code](https://github.com/Unleash/unleash-client-dotnet/blob/8158ccf9485e2433896609deff5faf2cb753de8d/src/Unleash/Scheduling/FetchFeatureTogglesTask.cs#L54) catches the `HttpRequestException` but do not catch the TaskCanceledException ([thrown by `SendAsync` when a timeout occurs](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.sendasync?view=net-7.0#system-net-http-httpclient-sendasync(system-net-http-httprequestmessage))).

**To Reproduce**

```cs
var settings = new UnleashSettings
{
    UnleashApi = new Uri("http://10.255.255.1/"), // just an address to force the timeout exception
};
var unleash = new UnleashClientFactory().CreateClient(settings, synchronousInitialization:true);
```

**Expected behavior**
The timeout exception should be handled, and the UnleashClient created.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser [e.g. chrome, safari]: N/A

**Comment by daveleek** [comment] 2023-08-09 04:39
Thank you for raising this @rafaelpadovezi, we'll have a look and get back to you!

**Comment by daveleek** [comment] 2023-08-15 09:54
Hi again @rafaelpadovezi. We've had a look and compared it with other SDKs and how it is intended to work.
Synchronous initialization is a blocking operation and should either block execution until features have been fetched and initialized, block until the request times out and then crash, or crash because the server is unavailable/server errors etc.

So it's intended behavior. Catching `HttpRequestException` was done to implement Error events however, and will be amended to work as intended in the synchronous initialization operation (it should crash).

Setting synchronous initialization to `false` should allow the behavior I think you are asking for - it will schedule a fetch but initialize the Unleash client and make that immediately available. Feature evaluations will resolve to `false` until features have been fetched and properly initialized. To address/work with this there are a few options:

###  [Local backups](https://github.com/Unleash/unleash-client-dotnet#local-backup)
Unleash will update a local backup every time it has fetched an updated set of features. This backup is attempted loaded during initialization of Unleash.

###  [Bootstrapping](https://github.com/Unleash/unleash-client-dotnet#bootstrapping)
You can bootstrap Unleash with a custom set of features during startup by providing a file

###  [Handling the update event](https://github.com/Unleash/unleash-client-dotnet#handling-events)
Unleash will raise a `TogglesUpdatedEvent` in the SDK every time it has updated its feature collection. You could subscribe to this event and trigger internal processes the first time this event is raised

**Comment by rafaelpadovezi** [comment] 2023-08-24 18:32
Thanks for the reply @daveleek.
> So it's intended behavior. Catching HttpRequestException was done to implement Error events however, and will be amended to work as intended in the synchronous initialization operation (it should crash).

Ok, makes sense! One thing that I would like you to consider it's to make it easier if I want to initialize synchoronously by default and asynchoronously if got some error.

I had to do the following to acomplish that:

```cs
try
{
    Unleash = unleashFactory.CreateClient(settings, synchronousInitialization: true);
}
 catch (Exception ex)
{
    settings.ScheduledTaskManager.Dispose();
    Unleash = unleashFactory.CreateClient(settings, synchronousInitialization: false);
}
```

One suggestion is to dispose everything created by the factory if `CreateClient` fails.

**Comment by daveleek** [comment] 2023-08-29 21:27
thank you @rafaelpadovezi - yes cleaning up should definitely be taken care of!
I'll have a look at fixing that!

**Comment by daveleek** [comment] 2023-09-06 09:55
Ok @rafaelpadovezi - I've had a look at it, and have discussed this with the team. Addressing this properly will require a re-architecture of the SDK and how it handles scheduling, and realigning with how we want our SDKs to work. It looks like you have a workaround that resolves the issue you've been experiencing, and we have other priorities ahead of this, so it's not going to be addressed right now.

**Comment by daveleek** [comment] 2023-09-25 07:03
I'm closing this issue now @rafaelpadovezi. But feel free to reopen or create a new issue if you have further questions!

**Closed by daveleek** 2023-09-25 07:03 UTC
